import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';

import {ReactElement, ReactNode} from 'react';

import StoreProvider from '@app/_providers/StoreProvider';
import {Header} from '@widgets/Header';

import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Shop Testing Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({
    children,
}: Readonly<{
    children: ReactNode;
}>): ReactElement => {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Header />
                <div className="content">
                    <StoreProvider>{children}</StoreProvider>
                </div>
            </body>
        </html>
    );
};

export default RootLayout;
